workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO##udistrital/}
  when:
      branch: [master, test]
      event: push

pipeline:

  # build and test the go program
  nodejs:
    image: node:10.7.0
    commands:
     - npm install -g grunt-cli bower
     - npm install natives
     - npm install
     - bower install --allow-root
     - grunt build

    when:
      branch: [master, test]
      event: push

  # upload app.zip to s3 bucket for CodePipline
  publish_s3:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: "us-east-1"
    commands:
     - case ${DRONE_BRANCH} in
          test) 
            BUCKET= pruebascliente
            ;;
          master) 
            BUCKET= pruebascliente1
            ;;
       esac 
     - echo $BUCKET     
    bucket: "$BUCKET"
    source: dist/**/*
    target: /${DRONE_REPO##udistrital/}.portaloas.udistrital.edu.co
    
    strip_prefix: dist/
    when:
      branch: [master, test]
      event: push
      
